# Change these first
owner: 9201314 # Your GitHub organization or username, where this repository lives
repo: u # The name of this repository

sites:
  - name: Hui.Ke
    url: https://hui.ke/
    expectedStatusCodes:
      - 200
      - 503
  - name: Hui.Ke - Blog
    url: https://b.hui.ke/
    expectedStatusCodes:
      - 200
      - 503
  - name: Hui.Ke - Forum
    url: https://f.hui.ke/
    expectedStatusCodes:
      - 200
      - 503
  - name: Hui.Ke - Photos & Pics & Ps
    url: https://p.hui.ke/
    expectedStatusCodes:
      - 200
      - 503
  - name: Hui.Ke - Search
    url: https://s.hui.ke/
    expectedStatusCodes:
      - 200
      - 503
  - name: Hui.Ke - Tools
    url: https://t.hui.ke/
    expectedStatusCodes:
      - 200
      - 503
  - name: Hui.Ke - Uptime
    url: https://u.hui.ke/
    expectedStatusCodes:
      - 200
      - 503

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: u.hui.ke
  # baseUrl: /your-repo-name
  logoUrl: https://hui.ke/favicon.ico
  name: Hui.Ke - Uptime
  introTitle: "Hui.Ke 站群运行状态监测 - SLA 99.999%"
  introMessage: 探针使用 GitHub Acitons 运行；网页使用 GitHub Pages 生成；访问使用 Cloudflare CDN 加速，故因网络问题，中国内地访问可能无法加载。
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

i18n:
  footer: Copyright © 2022 - Now [Hui.Ke](https://hui.ke/) Some Rights Reserved.

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
